name: auth_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^2.14.0
  dotenv: ^4.2.0
  http: ^1.2.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.11
  shelf_router_generator: ^1.1.0
  lints: ^3.0.0
